<a href="https://colab.research.google.com/github/rushikeshlokhande1/Data-Analysis_Pratice/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x=torch.tensor([1,2,3,4,5,6])  #1D tensor

In [3]:
print(x)

tensor([1, 2, 3, 4, 5, 6])


In [4]:
y=torch.tensor([[1,2,3,4],[5,6,7,8]])

In [5]:
print(y)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [8]:
torch.zeros((3,2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [10]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [11]:
torch.rand((2,3))

tensor([[0.4002, 0.0055, 0.5959],
        [0.1384, 0.6586, 0.9028]])

In [12]:
y.shape

torch.Size([2, 4])

In [14]:
x[1]

tensor(2)

In [17]:
print(y[0,2])

tensor(3)


In [21]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
print(a+b)
print(a*b)
print(a*2)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([2, 4, 6])


In [22]:
import numpy as np

In [24]:
arr=np.array([1,2,3,4,5])
n=torch.from_numpy(arr)
print(n)

tensor([1, 2, 3, 4, 5])


In [25]:
#Linear algebra
import torch
x=torch.tensor([1.0,2.0,3.0,4.0])
y=torch.tensor([2.0,3.0,4.0,5.0])
m=torch.tensor([0.0])
c=torch.tensor([0.0])

y_pred=m*x+c

loss_fun=((y_pred-y)**2).mean()
print("Predicated Value",y_pred)
print("Actual Value",y)
print("Loss Value",loss_fun)

Predicated Value tensor([0., 0., 0., 0.])
Actual Value tensor([2., 3., 4., 5.])
Loss Value tensor(13.5000)


In [ ]:
#Autograd and training
""" #Required Grade
"""

In [34]:
import torch
x=torch.tensor(2.0)
y=torch.tensor(4.0,requires_grad=True)
y_true=torch.tensor(10)
y_pred=x*y
loss_fun=((y_pred-y_true)**2).mean()
print(loss_fun)
loss_fun.backward()
print(y.grad)

tensor(4., grad_fn=<MeanBackward0>)
tensor(-8.)


In [37]:
import torch

# Training data
x = torch.tensor([1., 2., 3., 4., 5.])
y = torch.tensor([2., 3., 4., 5., 6.])

# Parameters (weight and bias)
w = torch.tensor(0.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

# Hyperparameters
lr = 0.1
epochs = 10

# Training loop
for epoch in range(epochs):
    # Forward pass
    y_pred = w * x + b

    # Compute loss (Mean Squared Error)
    loss = ((y_pred - y) ** 2).mean()

    # Backward pass
    loss.backward()

    # Update parameters
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad

    # Reset gradients
    w.grad.zero_()
    b.grad.zero_()

    # Print progress every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(
            f"Epoch {epoch+1}: "
            f"w = {w.item():.4f}, "
            f"b = {b.item():.4f}, "
            f"loss = {loss.item():.6f}"
        )

print("\nTraining Complete!")
print(f"Learned Weight (w): {w.item():.4f}")
print(f"Learned Bias (b): {b.item():.4f}")
import torch

# Training data
x = torch.tensor([1., 2., 3., 4., 5.])
y = torch.tensor([2., 3., 4., 5., 6.])

# Parameters (weight and bias)
w = torch.tensor(0.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

# Hyperparameters
lr = 0.01
epochs = 1000

# Training loop
for epoch in range(epochs):
    # Forward pass
    y_pred = w * x + b

    # Compute loss (Mean Squared Error)
    loss = ((y_pred - y) ** 2).mean()

    # Backward pass
    loss.backward()

    # Update parameters
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad

    # Reset gradients
    w.grad.zero_()
    b.grad.zero_()

    # Print progress every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(
            f"Epoch {epoch+1}: "
            f"w = {w.item():.4f}, "
            f"b = {b.item():.4f}, "
            f"loss = {loss.item():.6f}"
        )

print("\nTraining Complete!")
print(f"Learned Weight (w): {w.item():.4f}")
print(f"Learned Bias (b): {b.item():.4f}")

# Test the model
test_x = torch.tensor([6.0])
predicted_y = w * test_x + b
print(f"\nFor x = {test_x.item()}, Predicted y = {predicted_y.item():.4f}")


Training Complete!
Learned Weight (w): -25.7337
Learned Bias (b): -6.9174
Epoch 100: w = 1.1326, b = 0.5214, loss = 0.041974
Epoch 200: w = 1.0945, b = 0.6589, loss = 0.021321
Epoch 300: w = 1.0673, b = 0.7569, loss = 0.010831
Epoch 400: w = 1.0480, b = 0.8267, loss = 0.005502
Epoch 500: w = 1.0342, b = 0.8765, loss = 0.002795
Epoch 600: w = 1.0244, b = 0.9120, loss = 0.001420
Epoch 700: w = 1.0174, b = 0.9373, loss = 0.000721
Epoch 800: w = 1.0124, b = 0.9553, loss = 0.000366
Epoch 900: w = 1.0088, b = 0.9681, loss = 0.000186
Epoch 1000: w = 1.0063, b = 0.9773, loss = 0.000095

Training Complete!
Learned Weight (w): 1.0063
Learned Bias (b): 0.9773

For x = 6.0, Predicted y = 7.0150
